### PR TITLE
Update for löve2d 0.10

### PR DESCRIPTION
**Pull request by HalosGhost**

### CODE REVIEW

**Comment by HalosGhost** [comment]
This is only the first few things to make `lakka-menu` compatible with 0.10. I also have a significant number of code cleanups I would like to provide.

**Comment by kivutar** [comment]
Thank you!

**Comment by HalosGhost** [comment]
@Kivutar, more than happy to! I'm a big fan of libretro/retroarch and I would love to see Lakka's UI become pretty solid. (I am planning to use it as my primary UI on the OpenPandora and the Pyra, at least for a little while.)

**Comment by kivutar** [comment]
You're aware that this love menu was just a prototype? The real one is coded in C in RetroArch now.

**Comment by HalosGhost** [comment]
Oh wow! I had no idea! I indeed did not know that (though I am a big fan of retroarch, I have not used it in some time; it is exciting to hear that its UI has had some update)!

(It might be worth adding a note to the README about that, by the way). :)

**Pull request merged**
